---
apiVersion: v1
kind: Service
metadata:
  name: python-test-svc
spec:
  selector:
    app: python-test
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test
  labels:
    app: python-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-test
  template:
    metadata:
      labels:
        app: python-test
    spec:
      containers:
      - name: python-test
        image: localhost:5000/frontend:1.0
        ports:
        - containerPort: 5001
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: python-test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - python-test.com
  rules:
  - host: python-test.com
    http:
      paths:
      - backend:
          serviceName: python-test-svc
          servicePort: 443